/* SPDX-License-Identifier: GPL-2.0
 *
 * Copyright 2020-2024 HabanaLabs, Ltd.
 * Copyright (C) 2023-2024, Intel Corporation.
 * All Rights Reserved.
 *
 */

/************************************
 ** This is an auto-generated file **
 **       DO NOT EDIT BELOW        **
 ************************************/

#ifndef ASIC_REG_NIC0_QPC0_AXUSER_QPC_RESP_REGS_H_
#define ASIC_REG_NIC0_QPC0_AXUSER_QPC_RESP_REGS_H_

/*****************************************
 *   NIC0_QPC0_AXUSER_QPC_RESP
 *   (Prototype: AXUSER)
 *****************************************
 */

#define NIC0_QPC0_AXUSER_QPC_RESP_HB_ASID 0x541FDC0

#define NIC0_QPC0_AXUSER_QPC_RESP_HB_MMU_BP 0x541FDC4

#define NIC0_QPC0_AXUSER_QPC_RESP_HB_STRONG_ORDER 0x541FDC8

#define NIC0_QPC0_AXUSER_QPC_RESP_HB_NO_SNOOP 0x541FDCC

#define NIC0_QPC0_AXUSER_QPC_RESP_HB_WR_REDUCTION 0x541FDD0

#define NIC0_QPC0_AXUSER_QPC_RESP_HB_RD_ATOMIC 0x541FDD4

#define NIC0_QPC0_AXUSER_QPC_RESP_HB_QOS 0x541FDD8

#define NIC0_QPC0_AXUSER_QPC_RESP_HB_RSVD 0x541FDDC

#define NIC0_QPC0_AXUSER_QPC_RESP_HB_EMEM_CPAGE 0x541FDE0

#define NIC0_QPC0_AXUSER_QPC_RESP_HB_CORE 0x541FDE4

#define NIC0_QPC0_AXUSER_QPC_RESP_E2E_COORD 0x541FDE8

#define NIC0_QPC0_AXUSER_QPC_RESP_HB_WR_OVRD_LO 0x541FDF0

#define NIC0_QPC0_AXUSER_QPC_RESP_HB_WR_OVRD_HI 0x541FDF4

#define NIC0_QPC0_AXUSER_QPC_RESP_HB_RD_OVRD_LO 0x541FDF8

#define NIC0_QPC0_AXUSER_QPC_RESP_HB_RD_OVRD_HI 0x541FDFC

#define NIC0_QPC0_AXUSER_QPC_RESP_LB_COORD 0x541FE00

#define NIC0_QPC0_AXUSER_QPC_RESP_LB_LOCK 0x541FE04

#define NIC0_QPC0_AXUSER_QPC_RESP_LB_RSVD 0x541FE08

#define NIC0_QPC0_AXUSER_QPC_RESP_LB_OVRD 0x541FE0C

#endif /* ASIC_REG_NIC0_QPC0_AXUSER_QPC_RESP_REGS_H_ */
