/* SPDX-License-Identifier: GPL-2.0
 *
 * Copyright 2020-2024 HabanaLabs, Ltd.
 * Copyright (C) 2023-2024, Intel Corporation.
 * All Rights Reserved.
 *
 */

/************************************
 ** This is an auto-generated file **
 **       DO NOT EDIT BELOW        **
 ************************************/

#ifndef ASIC_REG_NIC0_QPC0_AXUSER_CONG_QUE_REGS_H_
#define ASIC_REG_NIC0_QPC0_AXUSER_CONG_QUE_REGS_H_

/*****************************************
 *   NIC0_QPC0_AXUSER_CONG_QUE
 *   (Prototype: AXUSER)
 *****************************************
 */

#define NIC0_QPC0_AXUSER_CONG_QUE_HB_ASID 0x541FB80

#define NIC0_QPC0_AXUSER_CONG_QUE_HB_MMU_BP 0x541FB84

#define NIC0_QPC0_AXUSER_CONG_QUE_HB_STRONG_ORDER 0x541FB88

#define NIC0_QPC0_AXUSER_CONG_QUE_HB_NO_SNOOP 0x541FB8C

#define NIC0_QPC0_AXUSER_CONG_QUE_HB_WR_REDUCTION 0x541FB90

#define NIC0_QPC0_AXUSER_CONG_QUE_HB_RD_ATOMIC 0x541FB94

#define NIC0_QPC0_AXUSER_CONG_QUE_HB_QOS 0x541FB98

#define NIC0_QPC0_AXUSER_CONG_QUE_HB_RSVD 0x541FB9C

#define NIC0_QPC0_AXUSER_CONG_QUE_HB_EMEM_CPAGE 0x541FBA0

#define NIC0_QPC0_AXUSER_CONG_QUE_HB_CORE 0x541FBA4

#define NIC0_QPC0_AXUSER_CONG_QUE_E2E_COORD 0x541FBA8

#define NIC0_QPC0_AXUSER_CONG_QUE_HB_WR_OVRD_LO 0x541FBB0

#define NIC0_QPC0_AXUSER_CONG_QUE_HB_WR_OVRD_HI 0x541FBB4

#define NIC0_QPC0_AXUSER_CONG_QUE_HB_RD_OVRD_LO 0x541FBB8

#define NIC0_QPC0_AXUSER_CONG_QUE_HB_RD_OVRD_HI 0x541FBBC

#define NIC0_QPC0_AXUSER_CONG_QUE_LB_COORD 0x541FBC0

#define NIC0_QPC0_AXUSER_CONG_QUE_LB_LOCK 0x541FBC4

#define NIC0_QPC0_AXUSER_CONG_QUE_LB_RSVD 0x541FBC8

#define NIC0_QPC0_AXUSER_CONG_QUE_LB_OVRD 0x541FBCC

#endif /* ASIC_REG_NIC0_QPC0_AXUSER_CONG_QUE_REGS_H_ */
