/* SPDX-License-Identifier: GPL-2.0
 *
 * Copyright 2020-2024 HabanaLabs, Ltd.
 * Copyright (C) 2023-2024, Intel Corporation.
 * All Rights Reserved.
 *
 */

/************************************
 ** This is an auto-generated file **
 **       DO NOT EDIT BELOW        **
 ************************************/

#ifndef ASIC_REG_NIC0_TMR_AXUSER_TMR_FREE_LIST_REGS_H_
#define ASIC_REG_NIC0_TMR_AXUSER_TMR_FREE_LIST_REGS_H_

/*****************************************
 *   NIC0_TMR_AXUSER_TMR_FREE_LIST
 *   (Prototype: AXUSER)
 *****************************************
 */

#define NIC0_TMR_AXUSER_TMR_FREE_LIST_HB_ASID 0x5448D60

#define NIC0_TMR_AXUSER_TMR_FREE_LIST_HB_MMU_BP 0x5448D64

#define NIC0_TMR_AXUSER_TMR_FREE_LIST_HB_STRONG_ORDER 0x5448D68

#define NIC0_TMR_AXUSER_TMR_FREE_LIST_HB_NO_SNOOP 0x5448D6C

#define NIC0_TMR_AXUSER_TMR_FREE_LIST_HB_WR_REDUCTION 0x5448D70

#define NIC0_TMR_AXUSER_TMR_FREE_LIST_HB_RD_ATOMIC 0x5448D74

#define NIC0_TMR_AXUSER_TMR_FREE_LIST_HB_QOS 0x5448D78

#define NIC0_TMR_AXUSER_TMR_FREE_LIST_HB_RSVD 0x5448D7C

#define NIC0_TMR_AXUSER_TMR_FREE_LIST_HB_EMEM_CPAGE 0x5448D80

#define NIC0_TMR_AXUSER_TMR_FREE_LIST_HB_CORE 0x5448D84

#define NIC0_TMR_AXUSER_TMR_FREE_LIST_E2E_COORD 0x5448D88

#define NIC0_TMR_AXUSER_TMR_FREE_LIST_HB_WR_OVRD_LO 0x5448D90

#define NIC0_TMR_AXUSER_TMR_FREE_LIST_HB_WR_OVRD_HI 0x5448D94

#define NIC0_TMR_AXUSER_TMR_FREE_LIST_HB_RD_OVRD_LO 0x5448D98

#define NIC0_TMR_AXUSER_TMR_FREE_LIST_HB_RD_OVRD_HI 0x5448D9C

#define NIC0_TMR_AXUSER_TMR_FREE_LIST_LB_COORD 0x5448DA0

#define NIC0_TMR_AXUSER_TMR_FREE_LIST_LB_LOCK 0x5448DA4

#define NIC0_TMR_AXUSER_TMR_FREE_LIST_LB_RSVD 0x5448DA8

#define NIC0_TMR_AXUSER_TMR_FREE_LIST_LB_OVRD 0x5448DAC

#endif /* ASIC_REG_NIC0_TMR_AXUSER_TMR_FREE_LIST_REGS_H_ */
