# SPDX-License-Identifier: GPL-2.0-only
#
# Makefile for HabanaLabs (an Intel Company) Ethernet network driver
#

obj-$(CONFIG_HABANA_EN) := habanalabs_en.o

include $(src)/common/Makefile
habanalabs_en-y += $(HBL_EN_COMMON_FILES)
